-- 整词录音。
-- 单字录音接起来播不等于真实语流：「你好」实际念 ní hǎo（三声变调），
-- 单字拼出来是 nǐ + hǎo。有字看时无所谓，到了纯听力档孩子就是照着
-- 这个音去记的，会学到不自然的语调。所以 L4 起要老师直接念整个词。

create table if not exists shared_word_audios (
  id bigint primary key generated by default as identity,
  word text not null unique,          -- 一个词一条，后录的覆盖前录的
  teacher_name text not null,
  audio_url text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists idx_shared_word_audios_word on shared_word_audios(word);

-- RLS：跟 shared_audios 一样按公开读写处理，登录入口本身有口令。
-- （建表默认开着 RLS 又没有策略，anon 写入会被 42501 拒掉。）
alter table shared_word_audios enable row level security;

drop policy if exists shared_word_audios_read   on shared_word_audios;
drop policy if exists shared_word_audios_write  on shared_word_audios;
drop policy if exists shared_word_audios_update on shared_word_audios;

create policy shared_word_audios_read   on shared_word_audios for select using (true);
create policy shared_word_audios_write  on shared_word_audios for insert with check (true);
create policy shared_word_audios_update on shared_word_audios for update using (true) with check (true);
