-- 创建共享音频表：老师上传的音频可被其他班级复用
create table if not exists shared_audios (
  id bigint primary key generated by default as identity,
  char_id bigint not null references characters(id) on delete cascade,
  teacher_name text not null,           -- 录音老师名字
  audio_url text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),

  -- 同一个字同一个老师最多一条记录
  unique(char_id, teacher_name),

  -- 便于查询某个字是否有共享音频
  unique(char_id, teacher_name)
);

-- 查询某字是否有共享音频的函数
create or replace function get_shared_audio(char_id_param bigint)
returns table(teacher_name text, audio_url text, created_at timestamp) as $$
begin
  return query
  select sa.teacher_name, sa.audio_url, sa.created_at
  from shared_audios sa
  where sa.char_id = char_id_param
  order by sa.created_at desc
  limit 1;
end;
$$ language plpgsql;

-- 为表建索引便于查询
create index if not exists idx_shared_audios_char_id on shared_audios(char_id);
create index if not exists idx_shared_audios_teacher on shared_audios(teacher_name);
