-- 水平测评结果。一次测评一行，三个板块的定级都放在 results 里。
-- results 形如：
--   {"recognize":{"passed":4,"capped":false},
--    "reading":{"passed":3,"capped":false},
--    "writing":{"passed":1,"capped":false}}
-- passed = 0 表示连最低那一级都没过；capped = true 表示题目做完了还在过，
-- 只能说「至少这么高」。

create table if not exists assessments (
  id bigint primary key generated by default as identity,
  class_id text not null,
  student_name text not null,
  results jsonb not null default '{}'::jsonb,
  taken_at timestamp with time zone default now()
);

create index if not exists idx_assessments_class on assessments(class_id, taken_at desc);
create index if not exists idx_assessments_student on assessments(student_name);

-- RLS：跟这个项目其它表一个口径。
-- 注意 DELETE 也一并放行 —— 前面几张表都因为漏了它，测试数据清不掉。
alter table assessments enable row level security;

drop policy if exists assessments_read   on assessments;
drop policy if exists assessments_write  on assessments;
drop policy if exists assessments_update on assessments;
drop policy if exists assessments_delete on assessments;

create policy assessments_read   on assessments for select using (true);
create policy assessments_write  on assessments for insert with check (true);
create policy assessments_update on assessments for update using (true) with check (true);
create policy assessments_delete on assessments for delete using (true);
